### ISSUE TITLE
ZHA in SBY stopped when zookeeper leader process down

### ISSUE THREAD

**Issue by bwtakacy** [sakamotomsh/zha#5]
From the stacktrace, there happened SessionExpiredError inside kazoo.

```
WARNING: 2015-12-25 15:17:45,504 Connection dropped: socket connection error: Connection refused
INFO: 2015-12-25 15:17:45,504 Connecting to oonishitk-pg1:2181
WARNING: 2015-12-25 15:17:45,520 Connection dropped: socket connection broken
INFO: 2015-12-25 15:17:45,683 Connecting to oonishitk-pg3:2181
WARNING: 2015-12-25 15:17:45,684 Connection dropped: socket connection error: Connection refused
INFO: 2015-12-25 15:17:45,685 Connecting to oonishitk-pg1:2181
INFO: 2015-12-25 15:17:45,690 Zookeeper connection established, state: CONNECTED
INFO: 2015-12-25 15:17:45,690 zookeeper connection state changed CONNECTED
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/postgres/zha/zha.py", line 284, in run
    self.in_elector_loop()
  File "/home/postgres/zha/zha.py", line 303, in in_elector_loop
    lock_result = self.lock.acquire(timeout=self.zha.config.get("elector_interval",3))
  File "/usr/lib/python2.6/site-packages/kazoo-2.2.1-py2.6.egg/kazoo/recipe/lock.py", line 174,
in acquire
    self._delete_node(self.node)
  File "/usr/lib/python2.6/site-packages/kazoo-2.2.1-py2.6.egg/kazoo/recipe/lock.py", line 266,
in _delete_node
    self.client.delete(self.path + "/" + node)
  File "/usr/lib/python2.6/site-packages/kazoo-2.2.1-py2.6.egg/kazoo/client.py", line 1293, in d
elete
    return self.delete_async(path, version).get()
  File "/usr/lib/python2.6/site-packages/kazoo-2.2.1-py2.6.egg/kazoo/handlers/utils.py", line 72
, in get
    raise self._exception
SessionExpiredError

INFO: 2015-12-25 15:17:46,473 Connecting to oonishitk-pg2:2181
INFO: 2015-12-25 15:17:46,477 Zookeeper connection established, state: CONNECTED
INFO: 2015-12-25 15:17:46,478 zookeeper connection state changed CONNECTED
INFO: 2015-12-25 15:17:47,027 State=(SBY:HEALTHY) TTL=(9,9) Threads=(ON,ON,OFF,)
ERROR: 2015-12-25 15:17:47,027 monitor/elector thread ended unexpectedly. Exit
INFO: 2015-12-25 15:17:49,183 cluster monitor thread stopped.
INFO: 2015-12-25 15:17:51,119 health monitor thread stopped.
INFO: 2015-12-25 15:17:51,120 ZHA: main thread stopped.
INFO: 2015-12-25 15:17:54,123 ZHA: main thread stopped.

```

**Comment by bwtakacy** [comment]
After some struggle with kazoo code, I have found that the below point in clinent.py at kazoo is doubtful.

```
 497     def _call(self, request, async_object):
 498         """Ensure there's an active connection and put the request in
 499         the queue if there is.
 500
 501         Returns False if the call short circuits due to AUTH_FAILED,
 502         CLOSED, EXPIRED_SESSION or CONNECTING state.
 503
 504         """
 505
 506         if self._state == KeeperState.AUTH_FAILED:
 507             async_object.set_exception(AuthFailedError())
 508             return False
 509         elif self._state == KeeperState.CLOSED:
 510             async_object.set_exception(ConnectionClosedError(
 511                 "Connection has been closed"))
 512             return False
 513         elif self._state in (KeeperState.EXPIRED_SESSION,
 514                              KeeperState.CONNECTING):
 515             async_object.set_exception(SessionExpiredError())
 516             return False
```

The last elif block raises SessionExpiredError even in KeeperState.CONNECTING.
This is what ZHA in SBY process encountered.

After modifying the code as below, ZHA process comes to survive against ZooKeeper leader process down.

```

 497
 498     def _call(self, request, async_object):
 499         """Ensure there's an active connection and put the request in
 500         the queue if there is.
 501
 502         Returns False if the call short circuits due to AUTH_FAILED,
 503         CLOSED, EXPIRED_SESSION or CONNECTING state.
 504
 505         """
 506
 507         if self._state == KeeperState.AUTH_FAILED:
 508             async_object.set_exception(AuthFailedError())
 509             return False
 510         elif self._state == KeeperState.CLOSED:
 511             async_object.set_exception(ConnectionClosedError(
 512                 "Connection has been closed"))
 513             return False
 514 #        elif self._state in (KeeperState.EXPIRED_SESSION,
 515 #                             KeeperState.CONNECTING):
 516         elif self._state == KeeperState.CONNECTING:
 517             self.logger.warning('_call is called during KeepserState.CONNECTING')
 518             return False
 519         elif self._state == KeeperState.EXPIRED_SESSION:
 520             self.logger.warning('SessionExpiredError from _call in client.py')
 521             async_object.set_exception(SessionExpiredError())
 522             return False
```

The catch of KeeperState.CONNECTING may be not necessary.
The above fix is just for debuggin.

Anyway, it seems to be not a bug of zha but a bug of  kazoo...

Regards,

**Comment by bwtakacy** [comment]
I reported to kazoo project as https://github.com/python-zk/kazoo/issues/374
